services:
  piston:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piston_api
    restart: unless-stopped
    environment:
      - PISTON_RUN_TIMEOUT=${PISTON_MAX_RUN_TIMEOUT_MS:-30000}
      - PISTON_COMPILE_TIMEOUT=30000
      - PISTON_RUN_MEMORY_LIMIT=${PISTON_MAX_MEMORY_LIMIT_BYTES:-512000000}
      - PISTON_COMPILE_MEMORY_LIMIT=${PISTON_MAX_MEMORY_LIMIT_BYTES:-512000000}
    ports:
      - '2000:2000'
    volumes:
      - piston_packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000
    privileged: true

volumes:
  piston_packages:
