services:
  piston:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piston_api
    restart: unless-stopped
    ports:
      - '2000:2000'
    volumes:
      - piston_packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000
    privileged: true

volumes:
  piston_packages:
