import { useEffect, useState } from 'react';
import { IScheduleEvent } from '@cp/shared';
import { EventCard } from './EventCard';
import { cn } from '../cn';

interface WeekGridProps {
  /** ISO short labels per day, length must equal `daysCount`. e.g. ["Mon 14", "Tue 15", …] */
  dayLabels: string[];
  /** Index 0..daysCount-1 of the column to highlight (today). -1 to disable. */
  todayIndex?: number;
  /** Minutes since 00:00 for the first time slot, e.g. 480 = 08:00 */
  startMinutes?: number;
  /** Minutes since 00:00 for the last time slot, e.g. 900 = 15:00 */
  endMinutes?: number;
  /** Slot interval in minutes, default 60 */
  stepMinutes?: number;
  /** Slot height in px */
  slotPx?: number;
  events: IScheduleEvent[];
  className?: string;
  onEventClick?: (event: IScheduleEvent) => void;
}

/**
 * Custom CSS-grid weekly calendar. Time column on the left, one column
 * per day across, events absolutely-positioned within each day column
 * by the parent (we compute offsets from `event.startMinutes`).
 */
export function WeekGrid({
  dayLabels,
  todayIndex = -1,
  startMinutes = 480, // 08:00
  endMinutes = 900,   // 15:00
  stepMinutes = 60,   // 60 minutes
  slotPx = 80,
  events,
  className,
  onEventClick,
}: WeekGridProps) {
  const daysCount = dayLabels.length;
  
  // Safe slot generation based on stepMinutes
  const slots: number[] = [];
  for (let m = startMinutes; m <= endMinutes; m += stepMinutes) {
    slots.push(m);
  }
  // Ensure we cover the actual range generated by steps
  const actualEndMinutes = slots[slots.length - 1] ?? endMinutes;
  const totalMinutes = actualEndMinutes - startMinutes;
  const totalPx = (totalMinutes / stepMinutes) * slotPx;

  // State to track current time for the live indicator
  const [nowMinutes, setNowMinutes] = useState<number | null>(() => {
    const now = new Date();
    return now.getHours() * 60 + now.getMinutes();
  });

  useEffect(() => {
    const timer = setInterval(() => {
      const now = new Date();
      setNowMinutes(now.getHours() * 60 + now.getMinutes());
    }, 60000);
    return () => clearInterval(timer);
  }, []);

  const showTimeIndicator =
    todayIndex >= 0 &&
    nowMinutes !== null &&
    nowMinutes >= startMinutes &&
    nowMinutes <= actualEndMinutes;

  const indicatorTop = showTimeIndicator
    ? ((nowMinutes! - startMinutes) / stepMinutes) * slotPx
    : 0;

  return (
    <div
      className={cn(
        'w-full overflow-x-auto bg-surface-container-lowest rounded-xl border border-outline-variant/50 shadow-sm transition-all duration-300',
        className
      )}
    >
      <div
        className="grid"
        style={{
          gridTemplateColumns: `80px repeat(${daysCount}, minmax(130px, 1fr))`,
          minWidth: `${80 + daysCount * 130}px`,
        }}
      >
        {/* Header row */}
        <div className="border-b border-outline-variant/40 bg-surface-container-low/80 backdrop-blur-sm sticky top-0 z-20" />
        {dayLabels.map((label, i) => {
          const isToday = i === todayIndex;
          return (
            <div
              key={label}
              className={cn(
                'p-sm text-center text-label-sm font-semibold border-b border-l border-outline-variant/40 bg-surface-container-low/80 backdrop-blur-sm sticky top-0 z-20 transition-colors',
                isToday && 'text-primary bg-primary/5 font-bold',
              )}
            >
              {isToday ? (
                <span className="inline-flex items-center gap-xs">
                  <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse" />
                  {label}
                </span>
              ) : (
                label
              )}
            </div>
          );
        })}

        {/* Time column */}
        <div className="relative border-r border-outline-variant/20 bg-surface-container-lowest/50 select-none" style={{ height: totalPx }}>
          {slots.map((m, i) => {
            const topPosition = slots.length > 1 ? (i / (slots.length - 1)) * totalPx : 0;
            return (
              <div
                key={m}
                className="absolute left-0 right-0 text-[11px] font-medium text-on-surface-variant/80 pr-sm text-right -translate-y-1/2 transition-all duration-200"
                style={{ top: topPosition }}
              >
                {minutesLabel(m)}
              </div>
            );
          })}
        </div>

        {/* Day columns */}
        {dayLabels.map((_, dayIdx) => {
          const dayEvents = events.filter((e) => e.day === dayIdx);
          const isToday = dayIdx === todayIndex;
          return (
            <div
              key={dayIdx}
              className={cn(
                'relative border-l border-outline-variant/40 transition-colors duration-200',
                isToday && 'bg-primary/[0.02]',
              )}
              style={{ height: totalPx }}
            >
              {/* Horizontal grid lines */}
              {slots.slice(1).map((_, i) => {
                const topPosition = slots.length > 1 ? ((i + 1) / (slots.length - 1)) * totalPx : 0;
                return (
                  <div
                    key={i}
                    className="absolute inset-x-0 border-t border-outline-variant/25 pointer-events-none"
                    style={{ top: topPosition }}
                    aria-hidden
                  />
                );
              })}

              {/* Current Time Indicator line */}
              {isToday && showTimeIndicator && (
                <div
                  className="absolute left-0 right-0 z-10 flex items-center pointer-events-none -translate-y-1/2"
                  style={{ top: indicatorTop }}
                >
                  <div className="w-2.5 h-2.5 rounded-full bg-primary shadow-md border-2 border-surface-container-lowest" />
                  <div className="flex-1 border-t-2 border-primary" />
                </div>
              )}

              {/* Events */}
              {dayEvents.map((evt) => {
                const top = ((evt.startMinutes - startMinutes) / stepMinutes) * slotPx;
                const height = (evt.durationMin / stepMinutes) * slotPx - 4;
                return (
                  <div
                    key={evt.id}
                    className="absolute inset-x-1 transition-all duration-300 hover:z-10"
                    style={{ top, height }}
                  >
                    <EventCard event={evt} onClick={() => onEventClick?.(evt)} />
                  </div>
                );
              })}
            </div>
          );
        })}
      </div>
    </div>
  );
}

function minutesLabel(m: number) {
  const hh = Math.floor(m / 60);
  const mm = m % 60;
  return `${hh.toString().padStart(2, '0')}:${mm.toString().padStart(2, '0')}`;
}
